// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Warren.Banking.Infra;
using Warren.Banking.Infra.Context;

namespace Warren.Banking.Infra.Migrations
{
    [DbContext(typeof(BankingContext))]
    [Migration("20210116222742_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.Account", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.Transaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("AccountId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OperationType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("OperationValue")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("TransactionsHistory");
                });

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.Account", b =>
                {
                    b.HasOne("Warren.Banking.Core.Aggregates.Acounts.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.Transaction", b =>
                {
                    b.HasOne("Warren.Banking.Core.Aggregates.Acounts.Account", null)
                        .WithMany("TransactionsHistory")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("Warren.Banking.Core.Aggregates.Acounts.Account", b =>
                {
                    b.Navigation("TransactionsHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
