version: "3.8"

services:
  banking-core-api:
    build:
      context: api/
    image: warren/banking-core-api
    container_name: banking-core-api
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
    networks:
      - banking-network
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    networks:
      - banking-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 20s
      retries: 10

  banking-core-app:
    build:
      context: app/
    image: warren/banking-core-app
    container_name: banking-core-app
    ports:
      - 3000:80
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    networks:
      - banking-network

networks:
  banking-network:
